/**
 * Entities — humans, agents, systems, contractors.
 *
 * The unified entity abstraction is the keystone: the kernel reasons about all of these
 * with the same primitives.
 */

import type { EntitySeed } from './types'

export const entities: EntitySeed[] = [
  // ── Humans ───────────────────────────────────────────────────────────────
  {
    _id: 'entity-sarah-chen',
    name: 'Sarah Chen',
    entityType: 'human',
    title: 'Chief Executive Officer',
    capabilityIds: ['cap-emergency-override', 'cap-budget-reallocation'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: null,
    departmentId: 'dept-executive',
    availability: 'business hours',
    riskProfile: 1,
    costProfile: 'premium',
  },
  {
    _id: 'entity-marcus-webb',
    name: 'Marcus Webb',
    entityType: 'human',
    title: 'VP Engineering',
    capabilityIds: ['cap-process-param'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-sarah-chen',
    departmentId: 'dept-engineering',
    availability: 'business hours',
    riskProfile: 2,
    costProfile: 'high',
  },
  {
    _id: 'entity-diego-ruiz',
    name: 'Diego Ruiz',
    entityType: 'human',
    title: 'VP Operations',
    capabilityIds: ['cap-line-adjustment', 'cap-emergency-override'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-sarah-chen',
    departmentId: 'dept-production',
    availability: 'business hours',
    riskProfile: 2,
    costProfile: 'high',
  },
  {
    _id: 'entity-amara-okafor',
    name: 'Amara Okafor',
    entityType: 'human',
    title: 'Chief Financial Officer',
    capabilityIds: ['cap-budget-reallocation'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-sarah-chen',
    departmentId: 'dept-finance',
    availability: 'business hours',
    riskProfile: 1,
    costProfile: 'high',
  },
  {
    _id: 'entity-lisa-park',
    name: 'Lisa Park',
    entityType: 'human',
    title: 'Director of Quality',
    capabilityIds: [],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-diego-ruiz',
    departmentId: 'dept-quality',
    availability: 'business hours',
    riskProfile: 1,
    costProfile: 'medium',
  },
  {
    _id: 'entity-tom-bradley',
    name: 'Tom Bradley',
    entityType: 'human',
    title: 'Maintenance Lead',
    capabilityIds: [
      'cap-machine-diagnostics',
      'cap-maintenance-scheduling',
      'cap-incident-response',
    ],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-diego-ruiz',
    departmentId: 'dept-maintenance',
    availability: 'on-call',
    riskProfile: 2,
    costProfile: 'medium',
  },
  {
    _id: 'entity-jin-tanaka',
    name: 'Jin Tanaka',
    entityType: 'human',
    title: 'Senior Process Engineer',
    capabilityIds: ['cap-process-param', 'cap-incident-response', 'cap-process-simulation'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-marcus-webb',
    departmentId: 'dept-engineering',
    availability: 'business hours',
    riskProfile: 2,
    costProfile: 'medium',
  },
  {
    _id: 'entity-ravi-patel',
    name: 'Ravi Patel',
    entityType: 'human',
    title: 'CNC Operator (Line 1)',
    capabilityIds: ['cap-tool-replenishment'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-diego-ruiz',
    departmentId: 'dept-production',
    availability: '24/7 shifts',
    riskProfile: 1,
    costProfile: 'medium',
  },
  {
    _id: 'entity-elena-volkov',
    name: 'Elena Volkov',
    entityType: 'human',
    title: 'CNC Operator (Line 2)',
    capabilityIds: ['cap-tool-replenishment'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-diego-ruiz',
    departmentId: 'dept-production',
    availability: '24/7 shifts',
    riskProfile: 1,
    costProfile: 'medium',
  },
  {
    _id: 'entity-karim-hassan',
    name: 'Karim Hassan',
    entityType: 'human',
    title: 'Quality Inspector',
    capabilityIds: ['cap-quality-inspection'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-lisa-park',
    departmentId: 'dept-quality',
    availability: 'business hours',
    riskProfile: 1,
    costProfile: 'medium',
  },

  // ── Agents ───────────────────────────────────────────────────────────────
  {
    _id: 'entity-engineering-agent',
    name: 'Engineering Agent',
    entityType: 'agent',
    title: 'Autonomous engineering assistant',
    capabilityIds: [
      'cap-process-param',
      'cap-incident-response',
      'cap-process-simulation',
    ],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-marcus-webb',
    departmentId: 'dept-engineering',
    availability: '24/7',
    riskProfile: 3,
    costProfile: 'low',
  },
  {
    _id: 'entity-maintenance-agent',
    name: 'Maintenance Agent',
    entityType: 'agent',
    title: 'Autonomous maintenance assistant',
    capabilityIds: [
      'cap-machine-diagnostics',
      'cap-maintenance-scheduling',
      'cap-incident-response',
    ],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-tom-bradley',
    departmentId: 'dept-maintenance',
    availability: '24/7',
    riskProfile: 3,
    costProfile: 'low',
  },
  {
    _id: 'entity-ceo-assistant-agent',
    name: 'CEO Assistant Agent',
    entityType: 'agent',
    title: 'Executive briefing agent',
    capabilityIds: [],
    permissionIds: [],
    constraintIds: [],
    reportsToId: 'entity-sarah-chen',
    departmentId: 'dept-executive',
    availability: '24/7',
    riskProfile: 4,
    costProfile: 'low',
  },

  // ── Systems ──────────────────────────────────────────────────────────────
  {
    _id: 'entity-cnc-1',
    name: 'CNC Machine 1',
    entityType: 'system',
    title: 'Line 1 CNC mill (5-axis)',
    capabilityIds: ['cap-tool-replenishment'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: null,
    departmentId: 'dept-production',
    availability: '24/7',
    riskProfile: 2,
    costProfile: 'high',
  },
  {
    _id: 'entity-cnc-2',
    name: 'CNC Machine 2',
    entityType: 'system',
    title: 'Line 2 CNC mill (3-axis) — currently degraded',
    capabilityIds: ['cap-tool-replenishment'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: null,
    departmentId: 'dept-production',
    availability: '24/7',
    riskProfile: 2,
    costProfile: 'high',
  },
  {
    _id: 'entity-cnc-3',
    name: 'CNC Machine 3',
    entityType: 'system',
    title: 'Line 3 CNC mill (3-axis)',
    capabilityIds: ['cap-tool-replenishment'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: null,
    departmentId: 'dept-production',
    availability: '24/7',
    riskProfile: 2,
    costProfile: 'high',
  },
  {
    _id: 'entity-process-simulator',
    name: 'Process Simulator',
    entityType: 'service',
    title: 'Digital-twin process simulation service',
    capabilityIds: ['cap-process-simulation'],
    permissionIds: [],
    constraintIds: [],
    reportsToId: null,
    departmentId: 'dept-engineering',
    availability: 'business hours',
    riskProfile: 1,
    costProfile: 'low',
  },

  // ── Contractors ──────────────────────────────────────────────────────────
  {
    _id: 'entity-apex-hydraulics',
    name: 'Apex Hydraulics',
    entityType: 'contractor',
    title: 'External hydraulics vendor',
    capabilityIds: [],
    permissionIds: [],
    constraintIds: [],
    reportsToId: null,
    departmentId: 'dept-maintenance',
    availability: 'on-call',
    riskProfile: 3,
    costProfile: 'medium',
  },
]
