/**
 * The task MCP server (M7 part 4): tools over an in-process MCP pair and over
 * real stdio, returning what the HTTP API returns. Run with `npm run host:test`.
 * Every token here is generated by the test and thrown away.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { join } from 'node:path'

import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js'
import { generateToken } from '@quicksilver/kernel/identity/tokens'
import { departmentAutonomy } from '@quicksilver/kernel/playbooks/operate'

import { parseHostConfig } from './config.ts'
import { QuicksilverHost } from './host.ts'
import { Logger } from './log.ts'
import { checkHostUrl, createTaskMcpServer, httpTaskBackend, TASK_TOOLS } from './mcp-tasks.ts'
import { MemoryShadowStore } from './shadow-api.ts'
import { MemoryTaskClientPersistence, TaskClientRegistry } from './task-clients.ts'
import { MemoryTaskStore, type TaskCatalog } from './tasks.ts'

const TENANT = 'nuera'
const CATALOG: TaskCatalog = {
  defaultCapabilityId: 'task.triage',
  capabilities: [
    { id: 'task.triage', name: 'Triage a request', description: 'A person reads it.', department: 'operations', baseRiskLevel: 4, reversible: true, operationalImpact: 1, uncertainty: 3 },
    { id: 'reports.brief', name: 'Answer from the company model', description: 'Read-only answer.', department: 'operations', baseRiskLevel: 0, reversible: true, operationalImpact: 0, uncertainty: 1 },
  ],
  policies: [],
}

async function start() {
  const { token: founderToken, tokenDigest } = generateToken()
  const clients = new TaskClientRegistry({ persistence: new MemoryTaskClientPersistence(), tenantId: TENANT })
  const a = await clients.add('desk-client', 'entity-founder')
  const b = await clients.add('other-client', 'entity-founder')
  const host = new QuicksilverHost(parseHostConfig({ tenantId: TENANT, http: { host: '127.0.0.1', port: 0 }, workflows: {}, tasks: { rateLimit: { burst: 100, perMinute: 600 } } }), {
    principals: [{ id: 'entity-founder', kind: 'human', tenantId: TENANT, roles: ['intent-provider'], tokenDigest }],
    logger: new Logger({ level: 'error', sink: { write: () => {} } }),
    tasks: {
      store: new MemoryTaskStore(),
      clients,
      catalog: CATALOG,
      autonomy: async (d) => departmentAutonomy(undefined, undefined, d),
      shadow: { store: new MemoryShadowStore(), intentId: 'tasks' },
    },
  })
  const { port } = await host.start()
  const base = `http://127.0.0.1:${port}`
  const api = (path: string, token: string, body?: unknown) => fetch(`${base}${path}`, {
    method: body === undefined ? 'GET' : 'POST',
    headers: { authorization: `Bearer ${token}`, ...(body !== undefined ? { 'content-type': 'application/json' } : {}) },
    ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
  }).then(async (r) => ({ status: r.status, body: await r.json() as any }))
  const connect = async (token: string) => {
    const [clientSide, serverSide] = InMemoryTransport.createLinkedPair()
    const server = createTaskMcpServer(httpTaskBackend({ baseUrl: base, token }))
    await server.connect(serverSide)
    const client = new Client({ name: 'test-client', version: '1.0.0' })
    await client.connect(clientSide)
    const call = async (name: string, args: Record<string, unknown> = {}) => {
      const r = await client.callTool({ name, arguments: args }) as { content: Array<{ text: string }>; isError?: boolean }
      return { isError: r.isError === true, body: JSON.parse(r.content[0]!.text) }
    }
    return { client, call, close: async () => { await client.close(); await server.close() } }
  }
  return { host, base, api, connect, tokens: { a: a.token, b: b.token, founder: founderToken }, close: () => host.stop({ abort: true }) }
}

/** The parts of a task that do not depend on which call created it. */
const shape = (t: any) => ({ status: t.status, route: t.decision.route, reasons: t.decision.reasons, kernel: t.decision.kernel, execution: t.execution?.mode, submittedBy: t.submittedBy })

test('the tools: five, none approves, and each says the kernel decides and a human approves in the console', async () => {
  const h = await start()
  const mcp = await h.connect(h.tokens.a)
  try {
    const { tools } = await mcp.client.listTools()
    assert.deepEqual(tools.map((t) => t.name).sort(), ['cancel_task', 'describe_capabilities', 'get_task', 'list_my_tasks', 'submit_task'])
    assert.equal(tools.some((t) => /approve|deny|grant/.test(t.name)), false)
    const submit = tools.find((t) => t.name === 'submit_task')!
    assert.match(submit.description!, /request, not a command/)
    assert.match(submit.description!, /kernel decides/)
    assert.match(submit.description!, /console/)
    assert.match(submit.description!, /by a human/)
    assert.equal(TASK_TOOLS.length, 5)
    const approve = await mcp.call('approve_task', { id: 'task-00000000000000000000' })
    assert.equal(approve.isError, true)
    assert.match(approve.body.error, /human approves/)
  } finally { await mcp.close(); await h.close() }
})

test('MCP tool calls return the same results as the HTTP API', async () => {
  const h = await start()
  const mcp = await h.connect(h.tokens.a)
  try {
    for (const args of [
      { objective: 'Look into late invoices.' },
      { objective: 'What changed this week?', capabilityId: 'reports.brief' },
      { objective: 'Summarize the patent claims.' },
      { objective: 'Pay the vendor.', capabilityId: 'finance.pay' },
    ]) {
      const viaApi = await h.api('/api/tasks', h.tokens.a, args)
      const viaMcp = await mcp.call('submit_task', args)
      assert.equal(viaMcp.isError, false)
      assert.deepEqual(shape(viaMcp.body.task), shape(viaApi.body.task), `same outcome for "${args.objective}"`)
      assert.equal(viaMcp.body.task.source, 'mcp')
      assert.equal(viaApi.body.task.source, 'api')
    }

    const created = (await mcp.call('submit_task', { objective: 'Check the stock count.', idempotencyKey: 'k-1' })).body.task
    assert.equal((await mcp.call('submit_task', { objective: 'Check the stock count.', idempotencyKey: 'k-1' })).body.task.id, created.id)
    assert.deepEqual((await mcp.call('get_task', { id: created.id })).body, (await h.api(`/api/tasks/${created.id}`, h.tokens.a)).body)
    assert.deepEqual((await mcp.call('list_my_tasks', { status: 'awaiting-approval' })).body, (await h.api('/api/tasks?status=awaiting-approval', h.tokens.a)).body)
    assert.deepEqual((await mcp.call('describe_capabilities')).body, (await h.api('/api/tasks/capabilities', h.tokens.a)).body)
    const caps = (await mcp.call('describe_capabilities')).body.capabilities
    assert.deepEqual(caps.map((c: { id: string }) => c.id), ['task.triage', 'reports.brief'])
    assert.equal(JSON.stringify(caps).includes('baseRiskLevel'), false, 'no policy or risk internals')

    const cancelled = await mcp.call('cancel_task', { id: created.id, reason: 'No longer needed.' })
    assert.equal(cancelled.body.task.status, 'cancelled')
    assert.equal((await mcp.call('submit_task', { objective: 'x', status: 'done' })).isError, true, 'unknown fields are refused')
  } finally { await mcp.close(); await h.close() }
})

test('MCP carries the client\'s own authority only: bad tokens fail, other clients\' tasks stay hidden', async () => {
  const h = await start()
  const mine = await h.connect(h.tokens.a)
  const other = await h.connect(h.tokens.b)
  const forged = await h.connect(generateToken().token)
  try {
    const t = (await mine.call('submit_task', { objective: 'Look into late invoices.' })).body.task
    const hidden = await other.call('get_task', { id: t.id })
    assert.equal(hidden.isError, true)
    assert.equal(hidden.body.code, 'not-found')
    assert.equal((await other.call('cancel_task', { id: t.id })).isError, true)
    const denied = await forged.call('submit_task', { objective: 'Anything.' })
    assert.equal(denied.isError, true)
    assert.match(denied.body.error, /bearer token/)
    // Only a human in the console approves it.
    assert.equal((await h.api(`/api/tasks/${t.id}/approve`, h.tokens.founder, { reason: 'Go ahead.' })).body.task.status, 'queued')
    assert.equal((await mine.call('get_task', { id: t.id })).body.task.status, 'queued')
  } finally { await mine.close(); await other.close(); await forged.close(); await h.close() }
})

test('the stdio server: a real process, token from the environment, stdout only MCP', async () => {
  const h = await start()
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: ['--experimental-strip-types', '--no-warnings', join(import.meta.dirname, 'mcp-tasks.ts')],
    env: { PATH: process.env.PATH ?? '', QUICKSILVER_TASK_TOKEN: h.tokens.a, QUICKSILVER_HOST_URL: h.base },
    stderr: 'pipe',
  })
  const client = new Client({ name: 'stdio-test', version: '1.0.0' })
  try {
    await client.connect(transport)
    const r = await client.callTool({ name: 'submit_task', arguments: { objective: 'What changed this week?', capabilityId: 'reports.brief' } }) as { content: Array<{ text: string }> }
    const task = JSON.parse(r.content[0]!.text).task
    assert.equal(task.source, 'mcp')
    assert.equal(task.submittedBy, 'client:desk-client')
    assert.equal(task.status, 'queued')
  } finally { await client.close(); await h.close() }

  assert.equal(checkHostUrl('http://127.0.0.1:8787'), undefined)
  assert.equal(checkHostUrl('https://quicksilver.example.org'), undefined)
  assert.match(checkHostUrl('http://quicksilver.example.org')!, /https/)
})
